name: Build ShapeUp

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build Solution (Release)
      run: dotnet build ShapeUp.sln --configuration Release --no-restore

    - name: Publish exe
      run: dotnet publish ShapeUp.sln --configuration Release --output ./publish --self-contained true --runtime win-x64

    - name: Upload exe as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ShapeUp-exe
        path: ./publish/
