name: ShapeUp

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build Solution (Release)
      run: dotnet build ShapeUp.sln --configuration Release --no-restore

    - name: Publish exe
      run: dotnet publish ShapeUp.sln --configuration Release --output ./publish --self-contained true --runtime win-x64

    - name: Upload exe as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ShapeUp-exe
        path: ./publish/

  release:
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Download exe artifact
      uses: actions/download-artifact@v3
      with:
        name: ShapeUp-exe
        path: ./release

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "v${{ github.run_number }}"
        name: "ShapeUp v${{ github.run_number }}"
        body: "Automated release for merge to main (build #${{ github.run_number }})"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload exe to Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./release/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
